export const inputsUserProfile = [
	{
		id: 1,
		name: 'username',
		type: 'text',
		placeholder: 'Username',
		errorMessage: 'Username must be 5-16 characters, no special characters!',
		label: 'Username',
	},
	{
		id: 2,
		name: 'fname',
		type: 'text',
		placeholder: 'Firstname',
		errorMessage: 'It should not contain numbers or special characters!',
		label: 'Firstname',
	},
	{
		id: 3,
		name: 'lname',
		type: 'text',
		placeholder: 'Lastname',
		errorMessage: 'It should not contain numbers or special characters!',
		label: 'Lastname',
	},
	{
		id: 4,
		name: 'email',
		type: 'email',
		placeholder: 'Email Address',
		errorMessage: 'It should be a valid email address!',
		label: 'Email Address',
	},
	{
		id: 5,
		name: 'pwd',
		type: 'password',
		placeholder: 'Password',
		errorMessage:
			'Password needs 8-20 chars: at least one letter, one number, and a special character! or it does not match with confirm password!',
		label: 'Password',
	},
	{
		id: 6,
		name: 'cpwd',
		type: 'password',
		placeholder: 'Confirm Password',
		errorMessage: 'Passwords do not match!',
		label: 'Confirm Password',
	},
	{
		id: 7,
		name: 'phone',
		type: 'text',
		placeholder: 'Phone',
		errorMessage: 'The phone number must be a valid number!',
		label: 'Phone',
	},
    {
        id: 8,
        name: 'bio',
        type: 'text',
        placeholder: 'Bio',
        errorMessage: 'Please add a short biography!',
        label: 'Bio',
    },
];
