// formConfig.js

export const inputs = [
	{
		id: 1,
		name: 'username',
		type: 'text',
		placeholder: 'Username',
		errorMessage: 'Username must be 5-16 characters, no special characters!',
		label: 'Username',
		// pattern: '^[A-Za-z0-9]{5,16}$',
		// required: true,
	},
	{
		id: 2,
		name: 'fname',
		type: 'text',
		placeholder: 'Firstname',
		errorMessage: 'It should not contain numbers or special characters!',
		label: 'Firstname',
		// pattern: '^[A-Za-z]+$',
		// required: true,
	},
	{
		id: 3,
		name: 'lname',
		type: 'text',
		placeholder: 'Lastname',
		errorMessage: 'It should not contain numbers or special characters!',
		label: 'Lastname',
		// pattern: '^[A-Za-z]+$',
		// required: true,
	},
	{
		id: 4,
		name: 'email',
		type: 'email',
		placeholder: 'Email Address',
		errorMessage: 'It should be a valid email address!',
		label: 'Email Address',
		// required: true,
	},
	{
		id: 5,
		name: 'pwd',
		type: 'password',
		placeholder: 'Password',
		errorMessage:
			'Password needs 8-20 chars: at least one letter, one number, and a special character!',
		label: 'Password',
		// pattern: '^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,20}$',
		// required: true,
	},
	{
		id: 6,
		name: 'cpwd',
		type: 'password',
		placeholder: 'Confirm Password',
		errorMessage: 'Passwords do not match!',
		label: 'Confirm Password',
		// required: true,
	},
	{
		id: 7,
		name: 'phone',
		type: 'text',
		placeholder: 'Phone',
		errorMessage: 'The phone number must be a valid number!',
		label: 'Phone',
		// required: true,
	},
];
